### PR TITLE
Fixed issue with missing headers in digest request.

### LINKED ISSUE #464: Config headers not added to digest request.
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [2.0.5]

#### Expected / Desired Behavior / Question
I want to be able to make non GET requests (modifying requests like POST, PUT, PATCH) to a SharePoint instance while not being on the SharePoint site when sending the request.

#### Observed Behavior
As the DigestCache doesn't apply the headers supplied in `pnp.setup()` where the Authorization headers are normally added, you get a 403 response anytime the digest is requested because you're doing a modyfying request.

#### Steps to Reproduce
Use pnp from an external web application that is on a different domain, and then do any modyfying request.

Inside the digestcache.ts file it uses the `HttpClient.fetchRaw()` method which doesn't apply any headers from the configuration object. Also the headers from the configuration are not explicitly added to the request. It should be possible to solve the issue by simply applying all headers from the configuration inside [digestcache.ts](https://github.com/SharePoint/PnP-JS-Core/blob/master/src/net/digestcache.ts#L33)

### PR DESCRIPTION
**Pull request by fela98**
| Q               | A
| --------------- | ---
| Bug fix?        | [x]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | fixes #464

### CODE REVIEW

**Comment by fela98** [comment]
Seriously? No comments, nothing? This fixes an in my opinion very critical bug which renders this library useless if you are using it outside of the SharePoint site and do any other requests than GET requests. It would be great to at least get some comments wether you think this is the right approach or not.

**Comment by patrick-rodgers** [comment]
Hi @fela98 - well, I've been on vacation and am just now trying to catch up on all the activities I have for my job, including my _volunteer_ responsibilities for this repo. I haven't had a chance to look at this yet but will. Your contribution is appreciated but would also appreciate a little better approach to collaboration on your side. Thanks!

**Comment by fela98** [comment]
I am sorry if I came across rude. I'm just trying to push this forward as our business depends heavily on this package, and this bug is currently a blocker for us.

Keep up the good work! 👍

**Comment by patrick-rodgers** [comment]
Merged, thanks for the PR - this will be rolled up into a beta release once I've been able to catch up with the issues list.

**Pull request merged**
