### PR TITLE
Attachment files add and delete methods basic implementation 

### PR DESCRIPTION
**Pull request by koltyakov**
| Q               | A
| --------------- | ---
| Bug fix?        | [ ]
| New feature?    | [x]
| New sample?      | [ ]
| Related issues?  | mentioned in #263

#### What's in this Pull Request?

This pull request introduces basic item's attachment files add and delete operations.

##### Add an attachment to the item

```javascript
var content = "binary/base64 content - bla bla bla";
var listRelativeUrl = "/sites/dev01/lists/custom01";
var itemId = 1;
var attachmentFileName = "MyFileName.txt";

$pnp.sp.web.getList(listRelativeUrl).items.getById(itemId).attachmentFiles.add(attachmentFileName, content).then(function() {
    console.log("Attachment has been added");
});
```

##### Delete an attachment in item

```javascript
var listRelativeUrl = "/sites/dev01/lists/custom01";
var itemId = 1;
var attachmentFileName = "MyFileName.txt";

$pnp.sp.web.getList(listRelativeUrl).items.getById(itemId).attachmentFiles.getByName(attachmentFileName).delete().then(function() {
    console.log("Attachment has been deleted");
});
```

### CODE REVIEW

**Comment by patrick-rodgers** [comment]
Thanks for this @koltyakov - I will try and have a look early next week but should be a great addition. I'll let you know if I have any notes. Thanks!

**Comment by patrick-rodgers** [comment]
Thanks Andrew, I moved a few things around and added some helper methods to get the file contents. Appreciate you submitting the PR!

**Comment by koltyakov** [comment]
Thank you, Patrick!

**Comment by winfinnit** [comment]
Hello, I am trying to add an attachment using this function in powershell, but unfortunately I can't get it working. Do you have sample how to use this in powershell?

**Pull request merged**
