### PR TITLE
patch for calculating the date for regional settings

### LINKED ISSUE #659: Determine time zone offset (with DST)
#### Category
[ ] Enhancement

[ ] Bug

[ x ] Question

#### Version

Please specify what version of the library you are using: [     3.0.3    ]

#### Expected / Desired Behavior / Question

Is it possible to determine the current time zone offset?
@koltyakov helped a lot by adding `RegionalSettings/TimeZone`, but this endpoint doesn't say if it is in DST or not, only what the DST value should be if it is in DST.

This is important in order to save date and time values the same way as SharePoint does without relying on client having same time zone as regional settings.  
SharePoint will save date and time in UTC, but +/- time zone.

### PR DESCRIPTION
**Pull request by patrick-rodgers**
| Q               | A
| --------------- | ---
| Bug fix?        | [X]
| New feature?    | [ ]
| New sample?      | [ ]
| Related issues?  | fixes #659 

#### What's in this Pull Request?

Update to fix issue with date calc in method

### CODE REVIEW

**Comment by koltyakov** [comment]
Time conversion to "local ISO string" looks valid. That was my mistake just converting to iso string without taking offset in mind last time.
 
Was there any issue with the test url of getting a timezone by id?
```typescript
it("Should return _api/web/regionalsettings/timezones(15)", () => {		
  expect(regionalsettings.timeZones.getById(15).toUrl())
    .to.match(toMatchEndRegex("_api/web/regionalsettings/timezones(15)"));		
});
```
Oh, I see that `timeZones.getById` implementation has been changed. I have some concerns about it, just a feeling, that it will be generating `/timezones/getbyid(${id})` and not `/timezones(${id})` and I'm just not sure... Let me check it tomorrow morning please before merging.

**Comment by patrick-rodgers** [comment]
Ya, have a look. My testing worked. That is just calling the method explicitly. I'll hold off on merging.

**Comment by koltyakov** [comment]
I've checked the changes. This limitation of getting the timezone by id with only POST method makes us impossible to chain `regionalSettings.timeZones.getById({id})` with other methods or props in one call.
By rewriting .get with .postCore in my previous implementation (which I think is a bit hack and hairy) it was possible to chain like `regionalSettings.timeZones.getById(15).utcToLocalTime(date)`, now it require `regionalSettings.timeZones.getById(15).then(timeZone => timeZone.localTimeToUTC(new Date()))`. But this `this.clone(TimeZones, `GetById(${id})`).postAsCore({}, spODataEntity(TimeZone))` is definetely more gracefull due to other library prospective and unification reasons.
Thank you, Patrick! P.S. All my internal testing for time zones also works now.

**Comment by patrick-rodgers** [comment]
Yes, I agree that not chaining is a bummer - but I view it as us just surfacing what exists in the API. Honestly the underlying source code just needs a small update to support that method as a get (just like getting an item by id) but that work will never happen. Sounds like you are good, so I am merging this. Thanks!

**Pull request merged**
