### PR TITLE
UserCustomAction method getById does not return anything, heres a fix for that.

### PR DESCRIPTION
**Pull request by tavikukko**
| Q               | A
| --------------- | ---
| Bug fix?        | [ x]
| New feature?    | [x ]
| New sample?      | [ ]
| Related issues?  | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

**UserCustomActions**, method **getById** does not return anything. It is requesting **_api/web/usercustomactions/('a605f1ac-ff47-41e9-bf9e-100fe39b544c')** which is wrong. 
The correct url is **_api/web/usercustomactions('a605f1ac-ff47-41e9-bf9e-100fe39b544c')** without **/** in between. This PR will fix that.

Also Implemented **delete** method for UserCustomAction class

Also added implementation to get proper error message when fetch succeeds but response.ok == false

### CODE REVIEW

**Comment by patrick-rodgers** [comment]
Thanks @tavikukko - I'll review this when I am back next week. First glance looks good!

**Comment by patrick-rodgers** [comment]
Hi @tavikukko - the usercustomeraction update looks great, though I am not sure about the update in httpclient. Can you provide a scenario where this change is needed?

**Comment by tavikukko** [comment]
I even think its a bug, but with out this update in httpclient:

$pnp.sp.web.lists.getByTitle("ImNotHere").get().then(function(result) {
    console.log(result);
}).catch(function(error) {
    console.log(error); //  --> **TypeError: Already read(…)**
});

and with the update, you get **json object** with error message "**List 'ImNotHere' does not exist at site with URL 'https://contoso.sharepoint.com/sites/demo'.**"

**Comment by tavikukko** [comment]
I see problem in [this](https://github.com/SharePoint/PnP-JS-Core/blob/e1e4139979d048ba26721968fc1b9e6483b8f142/src/sharepoint/rest/queryable.ts#L336) code block, I think it should not read the response because you cannot read it afterwards (thats why there is the **TypeError** message in the .catch block). Instead, we could catch the bad request earlier (in the PR) and return the json which contains the correct error message from SharePoint rest api.

**Comment by patrick-rodgers** [comment]
So have fixed this in a slightly different way. I ended up returning a promise from the processHttpClientResponse method which logs the issue and then rejects. Issue was tied to the fact that once the body was read it allowed the flow to continue which then ended up calling the assigned parser. This way HttpClient stays "dumb" and we are handling the odata response in the right place. So the bug you found is fixed, though not yet checked in.

SO...if you could back out that part of this PR I can work on getting it merged next week and will definitely be part of 2.0.0. Thanks for the work on this!

**Comment by tavikukko** [comment]
No problem, reverted the commits from HttpClient.

**Comment by patrick-rodgers** [comment]
Thanks @tavikukko!

**Pull request merged**
